# Generated by Django 6.0.5 on 2026-05-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblecontroller',
            name='security_level',
            field=models.CharField(default='High (Encrypted)', max_length=50),
        ),
    ]
