# Generated by Django 6.0.5 on 2026-05-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ansiblecontroller_security_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.TimeField()),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playbook')),
            ],
        ),
    ]
