# Generated by Django 6.0.5 on 2026-05-18 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scheduledtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['execution_time'], 'verbose_name': 'Scheduled Task', 'verbose_name_plural': 'Scheduled Tasks'},
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='execution_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0 for Monday, 6 for Sunday', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=10),
        ),
    ]
