# Generated by Django 6.0.5 on 2026-05-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_scheduledtask_options_scheduledtask_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
