# Generated by Django 6.0.5 on 2026-05-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='category',
            field=models.CharField(choices=[('system', 'System & Health Checks'), ('database', 'Database Management Operations'), ('security', 'Security Infrastructure Hardening'), ('deployment', 'Application Lifecycle Deployment')], default='system', max_length=50),
        ),
    ]
