# Generated by Django 6.0.6 on 2026-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ansiblecontroller_ssh_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblecontroller',
            name='base_playbook_path',
            field=models.CharField(default='/home/ansible/playbooks', help_text='Remote directory where playbooks are located', max_length=255),
        ),
        migrations.AddField(
            model_name='ansiblecontroller',
            name='ssh_port',
            field=models.IntegerField(default=22, help_text='Default SSH port is 22'),
        ),
    ]
