# Generated by Django 6.0.6 on 2026-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ansiblecontroller_base_playbook_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
