# Generated by Django 6.0.6 on 2026-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_taskexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutionlog',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
