# Generated by Django 6.0.6 on 2026-07-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_taskexecutionlog_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutionlog',
            name='controller_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
