# Generated by Django 6.0.6 on 2026-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_taskexecutionlog_controller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblecontroller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ansiblecontroller',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
