# Generated by Django 6.0.6 on 2026-07-15 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ansiblecontroller_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('last_pulled', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_playbooks', to='core.ansiblecontroller')),
            ],
            options={
                'unique_together': {('controller', 'name')},
            },
        ),
    ]
