# Generated by Django 6.0.5 on 2026-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblecontroller',
            name='ssh_password',
            field=models.CharField(blank=True, help_text='Leave blank if using SSH keys', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ansiblecontroller',
            name='ssh_username',
            field=models.CharField(default='ubuntu', max_length=50),
        ),
    ]
