# Generated by Django 6.0.5 on 2026-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ansiblecontroller_ssh_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblecontroller',
            name='ssh_private_key',
            field=models.TextField(blank=True, help_text='Paste private key block if not using passwords', null=True),
        ),
    ]
