# Generated by Django 6.0.6 on 2026-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_playbook_definition_alter_playbook_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionlog',
            name='playbook',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='playbook',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='playbook',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ansiblecontroller',
            name='base_playbook_path',
        ),
        migrations.RemoveField(
            model_name='ansiblecontroller',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ansiblecontroller',
            name='security_level',
        ),
        migrations.RemoveField(
            model_name='ansiblecontroller',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='ansiblecontroller',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='ansiblecontroller',
            name='ssh_private_key',
        ),
        migrations.AddField(
            model_name='ansiblecontroller',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ansiblecontroller',
            name='playbook_directory',
            field=models.CharField(default='/home/ubuntu/playbooks', max_length=255),
        ),
        migrations.AddField(
            model_name='ansiblecontroller',
            name='ssh_key_path',
            field=models.CharField(default='/home/ubuntu/.ssh/id_rsa', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ansiblecontroller',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ansiblecontroller',
            name='ssh_username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='AccessGroup',
        ),
        migrations.DeleteModel(
            name='ExecutionLog',
        ),
        migrations.DeleteModel(
            name='Playbook',
        ),
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
