# Generated by Django 6.0.6 on 2026-07-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_executionlog_playbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansiblecontroller',
            name='ssh_key_path',
        ),
        migrations.AddField(
            model_name='ansiblecontroller',
            name='ssh_private_key',
            field=models.TextField(default='dummy_key'),
            preserve_default=False,
        ),
    ]
