# Generated by Django 6.0.6 on 2026-07-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usergroup_playbookassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookassignment',
            name='input_parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
